### ISSUE TITLE
Make LinkedList a doubly LinkedList

### ISSUE THREAD

**Issue by chasebish** [bdourdoufis/cs4500assignment1part2#8]
Assuming that the Queue is supposed to be first in, first out, changing to a doubly linked-list would make popping O(1) instead of O(n) with your current implementation. The spec says "it is likely that the application will push and pop extremely frequently" so this addition would be beneficial.

**Comment by SamedhG** [comment]
(Not the API designer) We tried doing a Doubly linked list by following the classic node and sentinel approach. Since these classes are mutually recursive and we are not allowed to place declarations in `.h` files with implemetations in `.cpp` files, we had a very hard time getting the file to even compile. If you have any ideas on how you would approach this problem, it would be very helpful

**Comment by mwaldrich** [comment]
Our Queue class no longer has a dependency on a LinkedList, so you are now free to implement it however you want.
